import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/navbar/Navbar";
import Footer from "@/components/shared/footer/Footer";
import { Manrope } from "next/font/google";

export const manrope = Manrope({
  subsets: ["latin"], // include the character sets you need
  weight: ["400", "500", "600", "700"], // specify required weights
  variable: "--font-manrope", // optional CSS variable
});

export const metadata: Metadata = {
  title: "Azlo | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
